import polars as pl

from Generator.crear_parquet import CreadorParquet

fuente397 = pl.DataFrame(
    {
        "TIPO_EVALUACION": pl.Series([], dtype=pl.Utf8),
        "TIPO_NEGOCIO": pl.Series([], dtype=pl.Utf8),
        "COD_NEGOCIO": pl.Series([], dtype=pl.Utf8),
        "TIPO_ENTIDAD": pl.Series([], dtype=pl.Utf8),
        "CODIGO_ENTIDAD": pl.Series([], dtype=pl.Utf8),
        "T_ENTIDAD_CONSORCIO": pl.Series([], dtype=pl.Utf8),
        "COD_ENTIDAD_CONSORCIO": pl.Series([], dtype=pl.Utf8),
        "TIPO_NEGOCIO_CONSORCIO": pl.Series([], dtype=pl.Utf8),
        "COD_NEGOCIO_CONSORCIO": pl.Series([], dtype=pl.Utf8),
        "TIPO_ID": pl.Series([], dtype=pl.Utf8),
        "IDENTIFICACION": pl.Series([], dtype=pl.Utf8),
        "DV": pl.Series([], dtype=pl.Utf8),
        "NOMBRE": pl.Series([], dtype=pl.Utf8),
        "CIIU": pl.Series([], dtype=pl.Utf8),
        "NATURALEZA": pl.Series([], dtype=pl.Utf8),
        "CAMPO1": pl.Series([], dtype=pl.Utf8),
        "CAMPO2": pl.Series([], dtype=pl.Utf8),
        "CAMPO3": pl.Series([], dtype=pl.Utf8),
        "CODIGORE": pl.Series([], dtype=pl.Utf8),
        "FORMATO": pl.Series([], dtype=pl.Utf8),
        "UNIDAD_CAPTURA": pl.Series([], dtype=pl.Utf8),
        "COLUMNA": pl.Series([], dtype=pl.Utf8),
        "SUBCUENTA": pl.Series([], dtype=pl.Utf8),
        "VALORES": pl.Series([], dtype=pl.Utf8),
        "FECHA_CORTE": pl.Series([], dtype=pl.Date),
        "IDDATOFUENTE": pl.Series([], dtype=pl.Int32),
    }
)


# Definir posibles valores para algunas columnas
posibles_valores = {
    "TIPO_EVALUACION": ["0"],
    "TIPO_NEGOCIO": ["0"],
    "COD_NEGOCIO": ["0"],
    "TIPO_ENTIDAD": ["0"],
    "CODIGO_ENTIDAD": ["0"],
    "T_ENTIDAD_CONSORCIO": ["0"],
    "COD_ENTIDAD_CONSORCIO": ["0"],
    "TIPO_NEGOCIO_CONSORCIO": ["0"],
    "COD_NEGOCIO_CONSORCIO": ["0"],
    "TIPO_ID": [""],
    "IDENTIFICACION": [""],
    "DV": [""],
    "NOMBRE": [""],
    "CIIU": [""],
    "NATURALEZA": [""],
    "CAMPO1": [""],
    "CAMPO2": [""],
    "CAMPO3": [""],
    "CODIGORE": [""],
    "FORMATO": ["397"],
    "UNIDAD_CAPTURA": ["1"],
    "COLUMNA": [str(i) for i in range(1, 37)],
    "SUBCUENTA": [str(i) for i in range(1, 9)],
    "VALORES": [
        "1",
        "153879",
        "98765",
        "4",
        "3",
        "890500678",
        "BANCO XYZ",
        "47",
        "20/11/2023",
        "20/11/2023",
        "30/06/2022",
        "110608",
        "230000000",
        "1,52",
        "678901",
        "130000000",
        "PESO",
        "0",
        "230000000",
        "PESO",
        "0",
        "230000000",
        "419080",
        "12345678",
        "135678",
        "123000000",
        "134560",
        "100000000",
        "3",
        "2",
        "134567",
        "134568",
        "3000000",
        "53000000",
        "2",
    ],
    "FECHA_CORTE": ["30/06/2023"],
}

creador = CreadorParquet(
    df_base=fuente397,
    posibles_valores=posibles_valores,
    columna_incremental="IDDATOFUENTE",
    output_path="fuentes/informes/f397.parquet",
)


creador.generar_datos(n_rows=6000000)
